<option value='ABRA'>ABRA</option>
<option value='AGUSAN DEL NORTE'>AGUSAN DEL NORTE</option>
<option value='AGUSAN DEL SUR'>AGUSAN DEL SUR</option>
<option value='AKLAN'>AKLAN</option>
<option value='ALBAY'>ALBAY</option>
<option value='ANTIQUE'>ANTIQUE</option>
<option value='BATAAN'>BATAAN</option>
<option value='BATANGAS'>BATANGAS</option>
<option value='BENGUET'>BENGUET</option>
<option value='BILIRAN'>BILIRAN</option>
<option value='BOHOL'>BOHOL</option>
<option value='BUKIDNON'>BUKIDNON</option>
<option value='BULACAN'>BULACAN</option>
<option value='CAGAYAN'>CAGAYAN</option>
<option value='CAMARINES NORTE'>CAMARINES NORTE</option>
<option value='CAMARINES SUR'>CAMARINES SUR</option>
<option value='CAPIZ'>CAPIZ</option>
<option value='CAVITE'>CAVITE</option>
<option value='CEBU'>CEBU</option>
<option value='COMPOSTELA VALLEY'>COMPOSTELA VALLEY</option>
<option value='COTABATO (NORTH COTABATO)'>COTABATO (NORTH COTABATO)</option>
<option value='DAVAO DEL NORTE'>DAVAO DEL NORTE</option>
<option value='DAVAO DEL SUR'>DAVAO DEL SUR</option>
<option value='DAVAO ORIENTAL'>DAVAO ORIENTAL</option>
<option value='EASTERN SAMAR'>EASTERN SAMAR</option>
<option value='GUIMARAS'>GUIMARAS</option>
<option value='ILOCOS NORTE'>ILOCOS NORTE</option>
<option value='ILOCOS SUR'>ILOCOS SUR</option>
<option value='ILOILO'>ILOILO</option>
<option value='ISABELA'>ISABELA</option>
<option value='KALINGA'>KALINGA</option>
<option value='LA UNION'>LA UNION</option>
<option value='LAGUNA'>LAGUNA</option>
<option value='LANAO DEL NORTE'>LANAO DEL NORTE</option>
<option value='LANAO DEL SUR'>LANAO DEL SUR</option>
<option value='LEYTE'>LEYTE</option>
<option value='MAGUINDANAO'>MAGUINDANAO</option>
<option value='MISAMIS OCCIDENTAL'>MISAMIS OCCIDENTAL</option>
<option value='MISAMIS ORIENTAL'>MISAMIS ORIENTAL</option>
<option value='NCR FIRST DISTRICT'>NCR FIRST DISTRICT</option>
<option value='NCR FOURTH DISTRICT'>NCR FOURTH DISTRICT</option>
<option value='NCR SECOND DISTRICT'>NCR SECOND DISTRICT</option>
<option value='NCR THIRD DISTRICT'>NCR THIRD DISTRICT</option>
<option value='NEGROS OCCIDENTAL'>NEGROS OCCIDENTAL</option>
<option value='NEGROS ORIENTAL'>NEGROS ORIENTAL</option>
<option value='NORTHERN SAMAR'>NORTHERN SAMAR</option>
<option value='NUEVA ECIJA'>NUEVA ECIJA</option>
<option value='NUEVA VIZCAYA'>NUEVA VIZCAYA</option>
<option value='OCCIDENTAL MINDORO'>OCCIDENTAL MINDORO</option>
<option value='ORIENTAL MINDORO'>ORIENTAL MINDORO</option>
<option value='PALAWAN'>PALAWAN</option>
<option value='PAMPANGA'>PAMPANGA</option>
<option value='PANGASINAN'>PANGASINAN</option>
<option value='QUEZON'>QUEZON</option>
<option value='QUIRINO'>QUIRINO</option>
<option value='RIZAL'>RIZAL</option>
<option value='SAMAR (WESTERN SAMAR)'>SAMAR (WESTERN SAMAR)</option>
<option value='SARANGANI'>SARANGANI</option>
<option value='SIQUIJOR'>SIQUIJOR</option>
<option value='SORSOGON'>SORSOGON</option>
<option value='SOUTH COTABATO'>SOUTH COTABATO</option>
<option value='SOUTHERN LEYTE'>SOUTHERN LEYTE</option>
<option value='SULTAN KUDARAT'>SULTAN KUDARAT</option>
<option value='SURIGAO DEL NORTE'>SURIGAO DEL NORTE</option>
<option value='SURIGAO DEL SUR'>SURIGAO DEL SUR</option>
<option value='TARLAC'>TARLAC</option>
<option value='ZAMBALES'>ZAMBALES</option>
<option value='ZAMBOANGA DEL NORTE'>ZAMBOANGA DEL NORTE</option>
<option value='ZAMBOANGA DEL SUR'>ZAMBOANGA DEL SUR</option>
<option value='ZAMBOANGA SIBUGAY'>ZAMBOANGA SIBUGAY</option>
